import type { Metadata } from "next";
import { Tilt_Neon } from "next/font/google";
import "./globals.css";

import { Partytown } from "@qwik.dev/partytown/react";
import Head from "next/head";

const tiltNeon = Tilt_Neon({
  subsets: ["latin"],
  variable: "--font-tilt-neon",
  weight: ["400"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <Partytown debug={true} forward={["dataLayer.push"]} />
      </Head>
      <body className={` ${tiltNeon.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
