import type { Metadata } from "next";
import { Sometype_Mono } from "next/font/google";
import "./globals.css";

import { Partytown } from "@qwik.dev/partytown/react";
import Head from "next/head";
import { AmplitudeProvider } from "../context";
import { LoaderProvider } from "../context/LoaderProvider";

const sometype_mono = Sometype_Mono({
  subsets: ["latin"],
  variable: "--font-sometype-mono",
  weight: "variable",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <script src="https://unpkg.com/three@0.134.0/build/three.min.js"></script>
        <script src="https://unpkg.com/vanta@0.5.24/dist/vanta.topology.min.js"></script>
        <Partytown debug={true} forward={["dataLayer.push"]} />
      </Head>
      <body className={` antialiased`}>
        <AmplitudeProvider>
          <LoaderProvider>
            {children}
          </LoaderProvider>
        </AmplitudeProvider>
      </body>
    </html>
  );
}
